[package]
name = "lox"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["jlox", "clox"]
default-members = ["clox"]

[workspace.dependencies]
anyhow = "1.0.95"
criterion = "0.6.0"
thiserror = "2.0.11"

[dev-dependencies]
regex = "1.5.4"
test-generator = "0.3.0"
